### ISSUE TITLE
./gradlew :system-tests:end2end-test:catalog-runtime:shadowJar returns error  Failed to create Jar file C:\Users\XXX\.gradle\caches\jars-9\87491e8cdb0229bafcb7120e23222513\jackson-core-2.15.2.jar.

### ISSUE THREAD

**Issue by xdxxxdx** [eclipse-edc/FederatedCatalog#127]
# Bug Report
### Observed Behavior
I followed the guide written in https://github.com/eclipse-edc/FederatedCatalog/blob/main/system-tests/end2end-test/README.md
When I run command:` ./gradlew :system-tests:end2end-test:catalog-runtime:shadowJar`
The system returns following error:
![image](https://github.com/eclipse-edc/FederatedCatalog/assets/15314807/6c95f353-81c1-4075-b952-26478c78b552)

### Expected Behavior
BUILD SUCCESSFUL should be returned

## Context Information

- Used version [e.g. EDC v1.0.0]
- OS: Windows 11 + WSL2
- java version "20.0.1" 2023-04-18

### Investigations
This issue doesn't occurs if I run:  gradle :system-tests:end2end-test:catalog-runtime:shadowJar
To use local configured gradle

```
PS C:\EDC\FederatedCatalog> gradle --version

------------------------------------------------------------
Gradle 8.2.1
------------------------------------------------------------

Build time:   2023-07-10 12:12:35 UTC
Revision:     a38ec64d3c4612da9083cc506a1ccb212afeecaa

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          20.0.1 (Oracle Corporation 20.0.1+9-29)
OS:           Windows 11 10.0 amd64
```

**Comment by ndr-brt** [comment]
could you please report the full stacktrace?
it could be related to java version... could you try it with the version 17? (the current supported one)

**Comment by xdxxxdx** [comment]
Java sdk 17 works, thanks
