### ISSUE TITLE
Query API: add authentication

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/FederatedCatalog#206]
# Feature Request

The Query-API needs authentication. It is assumed that the requirements in terms of security and reachability are identical to those of EDC's management API.
In other words the Query-API is just an extension to EDC's management API, so its also possible to simply put it under the `management-api` context. Then we'd have the same authentication (Delegated + TokenBased), the same deployment (port+path) and the same ingress infrastructure (validators, transformers, json-ld interceptors). This comes in especially handy if the FC is embedded in an EDC runtime.

## Which Areas Would Be Affected?

`federated-catalog-api`

## Why Is the Feature Desired?

security, consistency

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by wolf4ood** [comment]
Securing the `catalog` context can now be achieved via configuration using the extension introduced [here](https://github.com/eclipse-edc/Connector/pull/4321)

 For example with token based authentication:
 
 ```
web.http.catalog.path=/api/catalog
web.http.catalog.port=8081
web.http.catalog.auth.type=tokenbased
web.http.catalog.auth.key=apiKey
 ```
