### ISSUE TITLE
Implement `SqlFederatedCatalogCache`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/FederatedCatalog#207]
# Feature Request

The `FederatedCatalogCache` stores the catalogs of all dataspace participants and caches them for easy and latency-free access.
We currently only have an in-mem variant of this, so should have a Postgres variant too.

## Which Areas Would Be Affected?

FederatedCatalogCache

## Why Is the Feature Desired?

feature parity with other stores

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by wolf4ood** [comment]
Closed by https://github.com/eclipse-edc/FederatedCatalog/pull/218
