### ISSUE TITLE
Internal Server Error When Querying Catalog with QuerySpec and filterExpression due to missing `JsonObjectToCriterionTransformer`

### ISSUE THREAD

**Issue by thomasrutger** [eclipse-edc/FederatedCatalog#266]
# Bug Report

## Describe the Bug

When providing a `QuerySpec` payload to `/v1alpha/catalog/query` with a `filterExpression`, an internal server error 500 is returned. For example: 
```
{
  "@context": [
    "https://w3id.org/edc/connector/management/v0.0.1"
  ],
  "@type": "QuerySpec",
  "filterExpression": [
    {
      "@type": "Criterion",
      "operandLeft": "id",
      "operator": "=",
      "operandRight": "asset"
    }
  ]
}
```

### Expected Behavior
I expect a returned catalog according to the QuerySpec

### Observed Behavior

A 500 Internal Server Error is returned

## Steps to Reproduce

Provide the above `QuerySpec` to `/v1alpha/catalog/query`.

## Detailed Description

The call fails due to a missing `JsonObjectToCriterionTransformer` in the 
"default context" (root) `TypeTransformerRegistry`. As such, the `QuerySpec` JsonObject fails to be transformed.

`FederatedCatalogCacheExtension.registerTransformers` does not register `JsonObjectToCriterionTransformer`.

## Possible Implementation

Add `transformerRegistry.register(new JsonObjectToCriterionTransformer());` to `FederatedCatalogCacheExtension.registerTransformers`. 

Other considerations: 
- Introduce a specific transformer `context` for the federated catalog API like the `management-api` instead of the root/default transformer context (or re-use the  `management-api` if applicable/possible.
- Move the registration of transformers to `FederatedCatalogApiExtension` instead of `FederatedCatalogCacheExtension`
- Add test coverage for requests that contain a QuerySpec to `FederatedCatalogApiControllerTest`.

**Comment by wolf4ood** [comment]
Hi @thomasrutger 

thanks for raising this, the possible implementation you propose should fix the issue.

In case we are open to contribution :)

**Comment by thomasrutger** [comment]
> Hi @thomasrutger
> 
> thanks for raising this, the possible implementation you propose should fix the issue.
> 
> In case we are open to contribution :)

I would be happy to contribute the fix. Should I incorporate my additional points in the PR? Since some of them are refactor proposals not entirely related to just this specific issue.

**Comment by wolf4ood** [comment]
I would apply the fix as you proposed and in case we can open a separated discussion/proposal on changing the transformer context for the federated catalog transformer registry
